### ISSUE TITLE
Second service added via Homebridge-MQTT not remembered on Homebridge restart

### ISSUE THREAD

**Issue by bohtho** [cflurin/homebridge-mqtt#89] opened 2019-11-02 20:23 UTC
Has anyone else encountered the same? When I add a second service to an accessory only the first is remembered on Homebridge restart. Both in Home.app and reading all of this plugin's config via MQTT. Is there a change in HomeKit in iOS 13.2 that messes this up ?

**Comment by cflurin** [comment] 2019-11-03 09:06
How did you add the accessory and the second service?
Could you post your topic and payload JSON definitions.

**Comment by faxioman** [comment] 2019-11-05 06:15
Try to reset your mqtt broker. A retained “delete” message (if you previously made some add/remove tests) could be the cause of this problem.

**Comment by bohtho** [comment] 2019-11-05 13:00
No such messages are retained on the MQTT broker.

Topic: `homebridge/to/add/service`

Payload:
```
{
    "name": "Sentralvarme",
    "service_name": "Bereder",
    "service": "HeaterCooler"
}
```

Added to an accessory that already have a thermostat service.

**Comment by cflurin** [comment] 2019-11-05 13:22
If you want to retain it in the MQTT broker, you have to set retain true.

But you don't need it, because all the settings of your accessories are stored in the `cachedAccessories` file (path: .homebridge/accessories/cachedAccessories)

Search for `Sentralvarme` in `cachedAccessories`.

If you add the service, what shows `homebridge/from/response` ?

**Comment by bohtho** [comment] 2019-11-05 21:38
The response is `success` when I add it.

But cachedAccessories is empty ... hm... are there other paths where a duplicate could be stored ? I use DietPi based on Raspbian. This is odd because all other accessories (created via MQTT) are restored perfectly.

**Comment by cflurin** [comment] 2019-11-06 09:10
In order to be able to help you I need more infos and exactly what you did.

1. Your versions? (homebridge, homebridge-mqtt)

2. Are you using other plugins?

3. Start homebridge in Debug mode
see https://github.com/nfarina/homebridge/wiki/Basic-Troubleshooting

and post you log here.

If you are using node-red, build a short test showing how your are adding the accessory and the service and upload the flow here and post the result in the debug tab.

**Comment by cflurin** [comment] 2019-11-16 14:57
No answer! closing for now.

**Closed by cflurin** 2019-11-16 14:57 UTC

**Comment by bohtho** [comment] 2019-11-16 15:24
My versions are all the latest as per today.

Other Homebridge plugins are Homebridge-Hue.

However I have not been able to reproduce on the latest restarts of Homebridge. Then it is suddenly cached after all. Dont know what happened. Closing issue is ok.
